name: Issue Template Enforcement

on:
  issues:
    types: [opened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
    - name: Check if issue follows the template
      uses: actions/github-script@v6
      with:
        script: |
          const issueBody = context.payload.issue.body;

          if (!issueBody) {
            // If the issue body is null or undefined, comment and exit
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "It seems that the issue body is empty. Please follow the issue template guidelines and provide the necessary details."
            });
            return;
          }

          const lowerCaseBody = issueBody.toLowerCase();
          const requiredSections = [
            "describe the problem or question",
            "to reproduce",
            "expected behavior",
            "screenshots, full error message and stack trace, and objective information",
            "additional context"
          ];

          let missingSections = requiredSections.filter(section => !lowerCaseBody.includes(section));

          if (missingSections.length > 0) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `It seems the issue you opened is missing some key sections from our template: ${missingSections.join(", ")}. Please update your issue to include these sections. For more information, refer to our [issue template](https://guidewireconfluence.atlassian.net/wiki/x/SB4OC).`
            });

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
          }
